In [10]:
import httpx
import json
import pandas as pd
import typing

# Scratch Functions

In [25]:
# All the base_urls with routes are always paginated and have results field into it.

def get_paginated_base_url_results(url: str) -> list:
    """This function gets all the paginated result URLs"""

    response = httpx.get(url)
    response_data: dict = response.json()
    url_results: list = response_data['results']

    if 'next' in response_data and response_data['next']:
        paginated_url_result: list = get_paginated_base_url_results(
            response_data['next'])
        url_results += paginated_url_result

    return url_results


get_paginated_base_url_results("https://pokeapi.co/api/v2/version-group/")

[{'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'},
 {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'},
 {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'},
 {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'},
 {'name': 'ruby-sapphire',
  'url': 'https://pokeapi.co/api/v2/version-group/5/'},
 {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'},
 {'name': 'firered-leafgreen',
  'url': 'https://pokeapi.co/api/v2/version-group/7/'},
 {'name': 'diamond-pearl',
  'url': 'https://pokeapi.co/api/v2/version-group/8/'},
 {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version-group/9/'},
 {'name': 'heartgold-soulsilver',
  'url': 'https://pokeapi.co/api/v2/version-group/10/'},
 {'name': 'black-white', 'url': 'https://pokeapi.co/api/v2/version-group/11/'},
 {'name': 'colosseum', 'url': 'https://pokeapi.co/api/v2/version-group/12/'},
 {'name': 'xd', 'url': 'https://pokeapi.co/api/v2/version-group/13/'},
 {'name': 'black-2-white-2',
  'url': 'https://pokeapi.co/api/v2/version-group/14/'},
 {'name': 'x-y', 'url': 'https://pokeapi.co/api/v2/version-group/15/'},
 {'name': 'omega-ruby-alpha-sapphire',
  'url': 'https://pokeapi.co/api/v2/version-group/16/'},
 {'name': 'sun-moon', 'url': 'https://pokeapi.co/api/v2/version-group/17/'},
 {'name': 'ultra-sun-ultra-moon',
  'url': 'https://pokeapi.co/api/v2/version-group/18/'},
 {'name': 'lets-go-pikachu-lets-go-eevee',
  'url': 'https://pokeapi.co/api/v2/version-group/19/'},
 {'name': 'sword-shield',
  'url': 'https://pokeapi.co/api/v2/version-group/20/'},
 {'name': 'the-isle-of-armor',
  'url': 'https://pokeapi.co/api/v2/version-group/21/'},
 {'name': 'the-crown-tundra',
  'url': 'https://pokeapi.co/api/v2/version-group/22/'},
 {'name': 'brilliant-diamond-shining-pearl',
  'url': 'https://pokeapi.co/api/v2/version-group/23/'},
 {'name': 'legends-arceus',
  'url': 'https://pokeapi.co/api/v2/version-group/24/'},
 {'name': 'scarlet-violet',
  'url': 'https://pokeapi.co/api/v2/version-group/25/'},
 {'name': 'the-teal-mask',
  'url': 'https://pokeapi.co/api/v2/version-group/26/'},
 {'name': 'the-indigo-disk',
  'url': 'https://pokeapi.co/api/v2/version-group/27/'},
 {'name': 'red-green-japan',
  'url': 'https://pokeapi.co/api/v2/version-group/28/'},
 {'name': 'blue-japan', 'url': 'https://pokeapi.co/api/v2/version-group/29/'},
 {'name': 'legends-za', 'url': 'https://pokeapi.co/api/v2/version-group/30/'},
 {'name': 'mega-dimension',
  'url': 'https://pokeapi.co/api/v2/version-group/31/'},
 {'name': 'champions', 'url': 'https://pokeapi.co/api/v2/version-group/32/'}]

In [21]:
response = httpx.get('https://pokeapi.co/api/v2/version-group/7/')

response.json()

{'generation': {'name': 'generation-iii',
  'url': 'https://pokeapi.co/api/v2/generation/3/'},
 'id': 7,
 'move_learn_methods': [{'name': 'level-up',
   'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
  {'name': 'egg', 'url': 'https://pokeapi.co/api/v2/move-learn-method/2/'},
  {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
  {'name': 'machine',
   'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}],
 'name': 'firered-leafgreen',
 'order': 11,
 'pokedexes': [{'name': 'kanto',
   'url': 'https://pokeapi.co/api/v2/pokedex/2/'}],
 'regions': [{'name': 'kanto', 'url': 'https://pokeapi.co/api/v2/region/1/'}],
 'versions': [{'name': 'firered',
   'url': 'https://pokeapi.co/api/v2/version/10/'},
  {'name': 'leafgreen', 'url': 'https://pokeapi.co/api/v2/version/11/'}]}

In [7]:
url = 'https://pokeapi.co/api/v2/pokemon/113/'

response_data = httpx.get(url).json()

response_data

{'abilities': [{'ability': {'name': 'natural-cure',
    'url': 'https://pokeapi.co/api/v2/ability/30/'},
   'is_hidden': False,
   'slot': 1},
  {'ability': {'name': 'serene-grace',
    'url': 'https://pokeapi.co/api/v2/ability/32/'},
   'is_hidden': False,
   'slot': 2},
  {'ability': {'name': 'healer',
    'url': 'https://pokeapi.co/api/v2/ability/131/'},
   'is_hidden': True,
   'slot': 3}],
 'base_experience': 395,
 'cries': {'latest': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/113.ogg',
  'legacy': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/113.ogg'},
 'forms': [{'name': 'chansey',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/113/'}],
 'game_indices': [{'game_index': 40,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 40,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 40,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 113,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 113,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 113,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 113,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 113,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 113,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 113,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 113,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 113,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 113,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 113,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 113,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 113,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 113,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 113,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 113,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 113,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}}],
 'height': 11,
 'held_items': [{'item': {'name': 'oval-stone',
    'url': 'https://pokeapi.co/api/v2/item/110/'},
   'version_details': [{'rarity': 50,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 50,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 50,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 50,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 50,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}}]},
  {'item': {'name': 'lucky-egg', 'url': 'https://pokeapi.co/api/v2/item/208/'},
   'version_details': [{'rarity': 5,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 5,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 5,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 5,
     'version': {'name': 'firered',
      'url': 'https://pokeapi.co/api/v2/version/10/'}},
    {'rarity': 5,
     'version': {'name': 'leafgreen',
      'url': 'https://pokeapi.co/api/v2/version/11/'}},
    {'rarity': 5,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 5,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 5,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 5,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 5,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 5,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 5,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}},
    {'rarity': 5,
     'version': {'name': 'black-2',
      'url': 'https://pokeapi.co/api/v2/version/21/'}},
    {'rarity': 5,
     'version': {'name': 'white-2',
      'url': 'https://pokeapi.co/api/v2/version/22/'}},
    {'rarity': 5,
     'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
    {'rarity': 5,
     'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
    {'rarity': 5,
     'version': {'name': 'omega-ruby',
      'url': 'https://pokeapi.co/api/v2/version/25/'}},
    {'rarity': 5,
     'version': {'name': 'alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version/26/'}}]},
  {'item': {'name': 'lucky-punch',
    'url': 'https://pokeapi.co/api/v2/item/233/'},
   'version_details': [{'rarity': 50,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 50,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}},
    {'rarity': 50,
     'version': {'name': 'black-2',
      'url': 'https://pokeapi.co/api/v2/version/21/'}},
    {'rarity': 50,
     'version': {'name': 'white-2',
      'url': 'https://pokeapi.co/api/v2/version/22/'}},
    {'rarity': 50,
     'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
    {'rarity': 50,
     'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
    {'rarity': 50,
     'version': {'name': 'omega-ruby',
      'url': 'https://pokeapi.co/api/v2/version/25/'}},
    {'rarity': 50,
     'version': {'name': 'alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version/26/'}},
    {'rarity': 50,
     'version': {'name': 'sun',
      'url': 'https://pokeapi.co/api/v2/version/27/'}},
    {'rarity': 50,
     'version': {'name': 'moon',
      'url': 'https://pokeapi.co/api/v2/version/28/'}},
    {'rarity': 50,
     'version': {'name': 'ultra-sun',
      'url': 'https://pokeapi.co/api/v2/version/29/'}},
    {'rarity': 50,
     'version': {'name': 'ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version/30/'}},
    {'rarity': 100,
     'version': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version/20/'}}]}],
 'id': 113,
 'is_default': True,
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/113/encounters',
 'moves': [{'move': {'name': 'pound',
    'url': 'https://pokeapi.co/api/v2/move/1/'},
   'version_group_details': [{'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 2,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 2,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 3,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 3,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 3,
     'version_group': {'name': 'sun-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 3,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 6,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 7,
     'version_group': {'name': 'brilliant-diamond-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 6,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 1,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'}}]},
  {'move': {'name': 'double-slap', 'url': 'https://pokeapi.co/api/v2/move/3/'},
   'version_group_details': [{'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 2,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 16,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'}},
    {'level_learned_at': 16,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
    {'level_learned_at': 16,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
    {'level_learned_at': 17,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'sun-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
    {'level_learned_at': 12,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 2,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'}},
    {'level_learned_at': 1,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': 2,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'}}]},
  {'move': {'name': 'mega-punch', 'url': 'https://pokeapi.co/api/v2/move/5/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',

In [8]:

key_rejections_dict = {
    'url': 'name',
    'symbol_icon': 'name_icon',
    'game_index': 'generation'
}

def clean_unwanted_keys(data_dict, key_rejections_dict):
    replaced_dict = data_dict
    for key in key_rejections_dict:
        if key in data_dict:
            # key present in the data_dict.
            replacement_key = key_rejections_dict[key]
            if replacement_key in data_dict:
                # Replacement key is also present.
                replaced_dict = data_dict[replacement_key]

                if isinstance(replaced_dict, dict):
                    # Checking if the replacement data is again dictionary.
                    replaced_dict = clean_unwanted_keys(replaced_dict, key_rejections_dict)
            else:
                break
    return replaced_dict


def walk_nested_data(data, key_rejections_dict):
    cleaned_data = None
    if isinstance(data, dict):
        cleaned_data = {}
        cleaned_data = clean_unwanted_keys(data, key_rejections_dict)
        if not isinstance(cleaned_data, str):
            for sub_data in cleaned_data:
                cleaned_data[sub_data] = walk_nested_data(
                    data[sub_data], key_rejections_dict
                )
    elif isinstance(data, list):
        cleaned_data = []
        for sub_data in data:
            cleaned_data.append(walk_nested_data(
                sub_data, key_rejections_dict))
    else:
        return data
        
    return cleaned_data


nested_response_data = walk_nested_data(response_data, key_rejections_dict)

In [9]:
nested_response_data

{'abilities': [{'ability': 'natural-cure', 'is_hidden': False, 'slot': 1},
  {'ability': 'serene-grace', 'is_hidden': False, 'slot': 2},
  {'ability': 'healer', 'is_hidden': True, 'slot': 3}],
 'base_experience': 395,
 'cries': {'latest': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/113.ogg',
  'legacy': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/113.ogg'},
 'forms': ['chansey'],
 'game_indices': [{'game_index': 40, 'version': 'red'},
  {'game_index': 40, 'version': 'blue'},
  {'game_index': 40, 'version': 'yellow'},
  {'game_index': 113, 'version': 'gold'},
  {'game_index': 113, 'version': 'silver'},
  {'game_index': 113, 'version': 'crystal'},
  {'game_index': 113, 'version': 'ruby'},
  {'game_index': 113, 'version': 'sapphire'},
  {'game_index': 113, 'version': 'emerald'},
  {'game_index': 113, 'version': 'firered'},
  {'game_index': 113, 'version': 'leafgreen'},
  {'game_index': 113, 'version': 'diamond'},
  {'game_index': 113, 'version': 'pearl'},
  {'game_index': 113, 'version': 'platinum'},
  {'game_index': 113, 'version': 'heartgold'},
  {'game_index': 113, 'version': 'soulsilver'},
  {'game_index': 113, 'version': 'black'},
  {'game_index': 113, 'version': 'white'},
  {'game_index': 113, 'version': 'black-2'},
  {'game_index': 113, 'version': 'white-2'}],
 'height': 11,
 'held_items': [{'item': 'oval-stone',
   'version_details': [{'rarity': 50, 'version': 'diamond'},
    {'rarity': 50, 'version': 'pearl'},
    {'rarity': 50, 'version': 'platinum'},
    {'rarity': 50, 'version': 'heartgold'},
    {'rarity': 50, 'version': 'soulsilver'}]},
  {'item': 'lucky-egg',
   'version_details': [{'rarity': 5, 'version': 'ruby'},
    {'rarity': 5, 'version': 'sapphire'},
    {'rarity': 5, 'version': 'emerald'},
    {'rarity': 5, 'version': 'firered'},
    {'rarity': 5, 'version': 'leafgreen'},
    {'rarity': 5, 'version': 'diamond'},
    {'rarity': 5, 'version': 'pearl'},
    {'rarity': 5, 'version': 'platinum'},
    {'rarity': 5, 'version': 'heartgold'},
    {'rarity': 5, 'version': 'soulsilver'},
    {'rarity': 5, 'version': 'black'},
    {'rarity': 5, 'version': 'white'},
    {'rarity': 5, 'version': 'black-2'},
    {'rarity': 5, 'version': 'white-2'},
    {'rarity': 5, 'version': 'x'},
    {'rarity': 5, 'version': 'y'},
    {'rarity': 5, 'version': 'omega-ruby'},
    {'rarity': 5, 'version': 'alpha-sapphire'}]},
  {'item': 'lucky-punch',
   'version_details': [{'rarity': 50, 'version': 'black'},
    {'rarity': 50, 'version': 'white'},
    {'rarity': 50, 'version': 'black-2'},
    {'rarity': 50, 'version': 'white-2'},
    {'rarity': 50, 'version': 'x'},
    {'rarity': 50, 'version': 'y'},
    {'rarity': 50, 'version': 'omega-ruby'},
    {'rarity': 50, 'version': 'alpha-sapphire'},
    {'rarity': 50, 'version': 'sun'},
    {'rarity': 50, 'version': 'moon'},
    {'rarity': 50, 'version': 'ultra-sun'},
    {'rarity': 50, 'version': 'ultra-moon'},
    {'rarity': 100, 'version': 'xd'}]}],
 'id': 113,
 'is_default': True,
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/113/encounters',
 'moves': [{'move': 'pound',
   'version_group_details': [{'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'red-blue'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'yellow'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'gold-silver'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'crystal'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'ruby-sapphire'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'emerald'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'diamond-pearl'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'platinum'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 2,
     'version_group': 'black-white'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'colosseum'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'xd'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 2,
     'version_group': 'black-2-white-2'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 3,
     'version_group': 'x-y'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 3,
     'version_group': 'omega-ruby-alpha-sapphire'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 3,
     'version_group': 'sun-moon'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 3,
     'version_group': 'ultra-sun-ultra-moon'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'lets-go-pikachu-lets-go-eevee'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 6,
     'version_group': 'sword-shield'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 7,
     'version_group': 'brilliant-diamond-shining-pearl'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 6,
     'version_group': 'scarlet-violet'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'red-green-japan'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 1,
     'version_group': 'blue-japan'}]},
  {'move': 'double-slap',
   'version_group_details': [{'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 2,
     'version_group': 'red-blue'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'gold-silver'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'crystal'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'ruby-sapphire'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'emerald'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 16,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'diamond-pearl'},
    {'level_learned_at': 16,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'platinum'},
    {'level_learned_at': 16,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'black-white'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'colosseum'},
    {'level_learned_at': 17,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'xd'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'black-2-white-2'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'x-y'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'omega-ruby-alpha-sapphire'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'sun-moon'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'ultra-sun-ultra-moon'},
    {'level_learned_at': 12,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'lets-go-pikachu-lets-go-eevee'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 2,
     'version_group': 'red-green-japan'},
    {'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': 2,
     'version_group': 'blue-japan'}]},
  {'move': 'mega-punch',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-blue'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'emerald'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-green-japan'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'blue-japan'}]},
  {'move': 'fire-punch',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'platinum'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'black-2-white-2'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'omega-ruby-alpha-sapphire'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'ultra-sun-ultra-moon'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'lets-go-pikachu-lets-go-eevee'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'scarlet-violet'}]},
  {'move': 'ice-punch',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'platinum'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'black-2-white-2'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'omega-ruby-alpha-sapphire'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'ultra-sun-ultra-moon'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'lets-go-pikachu-lets-go-eevee'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'scarlet-violet'}]},
  {'move': 'thunder-punch',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'platinum'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'black-2-white-2'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'omega-ruby-alpha-sapphire'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'ultra-sun-ultra-moon'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'lets-go-pikachu-lets-go-eevee'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'scarlet-violet'}]},
  {'move': 'mega-kick',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-blue'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'emerald'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-green-japan'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'blue-japan'}]},
  {'move': 'headbutt',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'gold-silver'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'crystal'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'lets-go-pikachu-lets-go-eevee'}]},
  {'move': 'tackle',
   'version_group_details': [{'level_learned_at': 1,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'legends-arceus'}]},
  {'move': 'body-slam',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-blue'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'emerald'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'xd'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'scarlet-violet'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-green-japan'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'blue-japan'}]},
  {'move': 'take-down',
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-blue'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 27,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'black-white'},
    {'level_learned_at': 27,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'black-2-white-2'},
    {'level_learned_at': 27,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'x-y'},
    {'level_learned_at': 27,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'omega-ruby-alpha-sapphire'},
    {'level_learned_at': 27,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'sun-moon'},
    {'level_learned_at': 27,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'ultra-sun-ultra-moon'},
    {'level_learned_at': 25,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'lets-go-pikachu-lets-go-eevee'},
    {'level_learned_at': 24,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'sword-shield'},
    {'level_learned_at': 24,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'brilliant-diamond-shining-pearl'},
    {'level_learned_at': 24,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'scarlet-violet'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'scarlet-violet'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-green-japan'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'blue-japan'}]},
  {'move': 'double-edge',
   'version_group_details': [{'level_learned_at': 54,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'red-blue'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'red-blue'},
    {'level_learned_at': 54,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 0,
     'move_learn_method': 'machine',
     'order': None,
     'version_group': 'yellow'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'gold-silver'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'crystal'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'ruby-sapphire'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'emerald'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'emerald'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'firered-leafgreen'},
    {'level_learned_at': 46,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'diamond-pearl'},
    {'level_learned_at': 46,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'platinum'},
    {'level_learned_at': 46,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'heartgold-soulsilver'},
    {'level_learned_at': 54,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'black-white'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'colosseum'},
    {'level_learned_at': 57,
     'move_learn_method': 'level-up',
     'order': None,
     'version_group': 'xd'},
    {'level_learned_at': 0,
     'move_learn_method': 'tutor',
     'order': None,
     'version_group': 'xd'},

In [25]:
pd.DataFrame(nested_response_data['game_indices'])

    game_index     version
0          180         red
1          180        blue
2          180      yellow
3            6        gold
4            6      silver
5            6     crystal
6            6        ruby
7            6    sapphire
8            6     emerald
9            6     firered
10           6   leafgreen
11           6     diamond
12           6       pearl
13           6    platinum
14           6   heartgold
15           6  soulsilver
16           6       black
17           6       white
18           6     black-2
19           6     white-2

In [55]:
unnested_moves = []
for idx in range(len(nested_response_data['moves'])):
    move_dict = nested_response_data['moves'][idx]

    move_name = nested_response_data['moves'][idx]['move']
    for version_detail in nested_response_data['moves'][idx]['version_group_details']:
        version_detail.update({'move': move_name})
        unnested_moves.append(version_detail)

move_data_df = pd.DataFrame(unnested_moves)


move_data_df[move_data_df['version_group'] ==
             'firered-leafgreen'].sort_values(['level_learned_at', 'move_learn_method', 'order']).reset_index(drop=True)

    level_learned_at move_learn_method  order      version_group          move
0                  0           machine    NaN  firered-leafgreen           cut
1                  0           machine    NaN  firered-leafgreen           fly
2                  0           machine    NaN  firered-leafgreen          roar
3                  0           machine    NaN  firered-leafgreen  flamethrower
4                  0           machine    NaN  firered-leafgreen    hyper-beam
5                  0           machine    NaN  firered-leafgreen      strength
6                  0           machine    NaN  firered-leafgreen    earthquake
7                  0           machine    NaN  firered-leafgreen           dig
8                  0           machine    NaN  firered-leafgreen         toxic
9                  0           machine    NaN  firered-leafgreen   double-team
10                 0           machine    NaN  firered-leafgreen    fire-blast
11                 0           machine    NaN  firered-leafgreen          rest
12                 0           machine    NaN  firered-leafgreen       protect
13                 0           machine    NaN  firered-leafgreen    steel-wing
14                 0           machine    NaN  firered-leafgreen       attract
15                 0           machine    NaN  firered-leafgreen        return
16                 0           machine    NaN  firered-leafgreen   frustration
17                 0           machine    NaN  firered-leafgreen     iron-tail
18                 0           machine    NaN  firered-leafgreen  hidden-power
19                 0           machine    NaN  firered-leafgreen     sunny-day
20                 0           machine    NaN  firered-leafgreen    rock-smash
21                 0           machine    NaN  firered-leafgreen        facade
22                 0           machine    NaN  firered-leafgreen   focus-punch
23                 0           machine    NaN  firered-leafgreen   brick-break
24                 0           machine    NaN  firered-leafgreen  secret-power
25                 0           machine    NaN  firered-leafgreen      overheat
26                 0           machine    NaN  firered-leafgreen    aerial-ace
27                 0           machine    NaN  firered-leafgreen   dragon-claw
28                 0             tutor    NaN  firered-leafgreen    mega-punch
29                 0             tutor    NaN  firered-leafgreen  swords-dance
30                 0             tutor    NaN  firered-leafgreen     mega-kick
31                 0             tutor    NaN  firered-leafgreen     body-slam
32                 0             tutor    NaN  firered-leafgreen   double-edge
33                 0             tutor    NaN  firered-leafgreen       counter
34                 0             tutor    NaN  firered-leafgreen  seismic-toss
35                 0             tutor    NaN  firered-leafgreen         mimic
36                 0             tutor    NaN  firered-leafgreen    rock-slide
37                 0             tutor    NaN  firered-leafgreen    substitute
38                 0             tutor    NaN  firered-leafgreen    blast-burn
39                 1          level-up    1.0  firered-leafgreen     heat-wave
40                 1          level-up    2.0  firered-leafgreen       scratch
41                 1          level-up    3.0  firered-leafgreen         growl
42                 1          level-up    4.0  firered-leafgreen         ember
43                 1          level-up    5.0  firered-leafgreen    metal-claw
44                 7          level-up    NaN  firered-leafgreen         ember
45                13          level-up    NaN  firered-leafgreen    metal-claw
46                20          level-up    NaN  firered-leafgreen   smokescreen
47                27          level-up    NaN  firered-leafgreen    scary-face
48                34          level-up    NaN  firered-leafgreen  flamethrower
49                36          level-up    NaN  firered-leafgreen   wing-attack
50                44          level-up    NaN  firered-leafgreen         slash
51                54          level-up    NaN  firered-leafgreen   dragon-rage
52                64          level-up    NaN  firered-leafgreen     fire-spin

# Extractor Tool Class

In [29]:
import httpx
import typing


class PokeApiExtractorTools:

    def __init__(self):
        # This map helps in cleaning up unuwanted keys from the response.
        self.KEY_REJECTION_MAP = {
            'url': 'name',
            'symbol_icon': 'name_icon',
            'game_index': 'generation'
        }
        self.VERSION_GROUP_TO_VERSION_MAP = self.get_version_group_to_version_map()

    def get_paginated_base_url_results(self, url: str) -> list:
        """This function gets all the paginated result URLs"""
        response = httpx.get(url)
        response_data: dict = response.json()
        url_results: list = response_data['results']

        if 'next' in response_data and response_data['next']:
            paginated_url_result: list = get_paginated_base_url_results(
                response_data['next'])
            url_results += paginated_url_result

        return url_results

    def get_version_group_to_version_map(self) -> dict:
        """This function gets the version_group_to_version_map details"""
        version_group_to_version_map: dict = {}

        versions_group_url: str = "https://pokeapi.co/api/v2/version-group/"
        version_group_url_list: list = self.get_paginated_base_url_results(
            versions_group_url
        )

        for url_name_map in version_group_url_list:
            version_result =  httpx.get(
                url_name_map['url']
            ).json()
            if 'versions' in version_result:
                version_group_to_version_map[url_name_map['name']] = [
                    version_name_map['name'] 
                    for version_name_map in version_result['versions']
                ]

        return version_group_to_version_map


    def __clean_unwanted_keys(self, data_dict: dict) -> dict:
        """This function cleans unwanted keys from the data."""
        replaced_dict = data_dict
        for key in self.KEY_REJECTION_MAP:
            if key in data_dict:
                # key present in the data_dict.
                replacement_key = self.KEY_REJECTION_MAP[key]
                if replacement_key in data_dict:
                    # Replacement key is also present.
                    replaced_dict = data_dict[replacement_key]

                    if isinstance(replaced_dict, dict):
                        # Checking if the replacement data is again dictionary.
                        replaced_dict = self.__clean_unwanted_keys(replaced_dict)
                else:
                    break
        return replaced_dict


    def walk_nested_data(self, data: typing.Union[dict, list, str]) -> dict:
        """This function walks across the entire data and cleans the unwanted keys"""
        cleaned_data = None
        if isinstance(data, dict):
            cleaned_data = {}
            cleaned_data = self.__clean_unwanted_keys(data)
            if not isinstance(cleaned_data, str):
                for sub_data in cleaned_data:
                    cleaned_data[sub_data] = walk_nested_data(
                        data[sub_data], key_rejections_dict
                    )
        elif isinstance(data, list):
            cleaned_data = []
            for sub_data in data:
                cleaned_data.append(walk_nested_data(
                    sub_data, key_rejections_dict))
        else:
            return data

        return cleaned_data

In [31]:
pokeapi_extractor_tools = PokeApiExtractorTools()

# Pokemon endpoint Scratch

In [34]:
url = 'https://pokeapi.co/api/v2/pokemon/113/'

response_data = httpx.get(url).json()

In [35]:
response_data.keys()

dict_keys(['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_stats', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight'])

Looking at the data, it would be better to create multiple tables for stats. This makes this data a little better.

In [54]:
url = "https://pokeapi.co/api/v2/location-area/2"
httpx.get(url).json()

{'encounter_method_rates': [{'encounter_method': {'name': 'old-rod',
    'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
   'version_details': [{'rate': 25,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rate': 25,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rate': 25,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'encounter_method': {'name': 'good-rod',
    'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
   'version_details': [{'rate': 50,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rate': 50,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rate': 50,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'encounter_method': {'name': 'super-rod',
    'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
   'version_details': [{'rate': 75,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rate': 75,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rate': 75,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'encounter_method': {'name': 'surf',
    'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
   'version_details': [{'rate': 10,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rate': 10,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rate': 10,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]}],
 'game_index': 2,
 'id': 2,
 'location': {'name': 'eterna-city',
  'url': 'https://pokeapi.co/api/v2/location/2/'},
 'name': 'eterna-city-area',
 'names': [{'language': {'name': 'en',
    'url': 'https://pokeapi.co/api/v2/language/9/'},
   'name': 'Eterna City'},
  {'language': {'name': 'de', 'url': 'https://pokeapi.co/api/v2/language/6/'},
   'name': 'Ewigenau'},
  {'language': {'name': 'fr', 'url': 'https://pokeapi.co/api/v2/language/5/'},
   'name': 'Vestigion'}],
 'pokemon_encounters': [{'pokemon': {'name': 'psyduck',
    'url': 'https://pokeapi.co/api/v2/pokemon/54/'},
   'version_details': [{'encounter_details': [{'chance': 60,
       'condition_values': [],
       'max_level': 30,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20},
      {'chance': 30,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20}],
     'max_chance': 90,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'encounter_details': [{'chance': 60,
       'condition_values': [],
       'max_level': 30,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20},
      {'chance': 30,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20}],
     'max_chance': 90,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'encounter_details': [{'chance': 60,
       'condition_values': [],
       'max_level': 30,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20},
      {'chance': 30,
       'condition_values': [],
       'max_level': 30,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20}],
     'max_chance': 90,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'pokemon': {'name': 'golduck',
    'url': 'https://pokeapi.co/api/v2/pokemon/55/'},
   'version_details': [{'encounter_details': [{'chance': 5,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 30},
      {'chance': 4,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 30},
      {'chance': 1,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20}],
     'max_chance': 10,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'encounter_details': [{'chance': 5,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 30},
      {'chance': 4,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 30},
      {'chance': 1,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20}],
     'max_chance': 10,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'encounter_details': [{'chance': 5,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20},
      {'chance': 4,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20},
      {'chance': 1,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'surf',
        'url': 'https://pokeapi.co/api/v2/encounter-method/5/'},
       'min_level': 20}],
     'max_chance': 10,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'pokemon': {'name': 'magikarp',
    'url': 'https://pokeapi.co/api/v2/pokemon/129/'},
   'version_details': [{'encounter_details': [{'chance': 60,
       'condition_values': [],
       'max_level': 6,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 4},
      {'chance': 30,
       'condition_values': [],
       'max_level': 7,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 3},
      {'chance': 5,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 4,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 1,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 40,
       'condition_values': [],
       'max_level': 20,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 15},
      {'chance': 15,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10}],
     'max_chance': 155,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'encounter_details': [{'chance': 60,
       'condition_values': [],
       'max_level': 6,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 4},
      {'chance': 30,
       'condition_values': [],
       'max_level': 7,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 3},
      {'chance': 5,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 4,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 1,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 40,
       'condition_values': [],
       'max_level': 20,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 15},
      {'chance': 15,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10}],
     'max_chance': 155,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'encounter_details': [{'chance': 60,
       'condition_values': [],
       'max_level': 6,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 4},
      {'chance': 30,
       'condition_values': [],
       'max_level': 7,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 3},
      {'chance': 5,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 4,
       'condition_values': [],
       'max_level': 10,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 1,
       'condition_values': [],
       'max_level': 15,
       'method': {'name': 'old-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/2/'},
       'min_level': 5},
      {'chance': 40,
       'condition_values': [],
       'max_level': 20,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 15},
      {'chance': 15,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10}],
     'max_chance': 155,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'pokemon': {'name': 'gyarados',
    'url': 'https://pokeapi.co/api/v2/pokemon/130/'},
   'version_details': [{'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 30},
      {'chance': 15,
       'condition_values': [],
       'max_level': 55,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 40}],
     'max_chance': 55,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 30},
      {'chance': 15,
       'condition_values': [],
       'max_level': 55,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 40}],
     'max_chance': 55,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 30},
      {'chance': 15,
       'condition_values': [],
       'max_level': 55,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 40}],
     'max_chance': 55,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'pokemon': {'name': 'barboach',
    'url': 'https://pokeapi.co/api/v2/pokemon/339/'},
   'version_details': [{'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 20,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 15},
      {'chance': 4,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10},
      {'chance': 1,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10}],
     'max_chance': 45,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 20,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 15},
      {'chance': 4,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10},
      {'chance': 1,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10}],
     'max_chance': 45,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 20,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 15},
      {'chance': 4,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10},
      {'chance': 1,
       'condition_values': [],
       'max_level': 25,
       'method': {'name': 'good-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/3/'},
       'min_level': 10}],
     'max_chance': 45,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]},
  {'pokemon': {'name': 'whiscash',
    'url': 'https://pokeapi.co/api/v2/pokemon/340/'},
   'version_details': [{'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 30},
      {'chance': 4,
       'condition_values': [],
       'max_level': 50,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 20},
      {'chance': 1,
       'condition_values': [],
       'max_level': 50,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 20}],
     'max_chance': 45,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 30},
      {'chance': 4,
       'condition_values': [],
       'max_level': 50,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 20},
      {'chance': 1,
       'condition_values': [],
       'max_level': 50,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 20}],
     'max_chance': 45,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'encounter_details': [{'chance': 40,
       'condition_values': [],
       'max_level': 40,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 30},
      {'chance': 4,
       'condition_values': [],
       'max_level': 55,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 40},
      {'chance': 1,
       'condition_values': [],
       'max_level': 55,
       'method': {'name': 'super-rod',
        'url': 'https://pokeapi.co/api/v2/encounter-method/4/'},
       'min_level': 40}],
     'max_chance': 45,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}}]}]}